

ALL:
	gcc -Iat-parser -Ihw-specific hw-specific/linux_uart.c at-parser/at_parser.c main.c -o a.app

WIN:
	gcc -Iat-parser -Ihw-specific hw-specific/win_uart.c at-parser/at_parser.c main.c -o a.app


